# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 748e21fb7d63bd725a1be0661221dc33c2d9c83ba5c8783eaa576901da67851154979892f72749538f21b5c80fd0ba2c051747680076da9ea104650f178d30fc

test:
  secret_key_base: 9a7dcd9fa946a566e93d12f098067213a4cd29ed4f524eb053c9b0c07488f90e11097bee4e834d6cf0f4e205235a7b3c890e89cc287eda587613b3c60681b563

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
